name: CI

on:
  push:
    branches:
    - master

jobs:
  firebase-deploy-static-pages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
