name: CI

on:
  push:
    branches:
    - master

jobs:
  firebase-deploy-static-pages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: Install firebase-tools (firebase's cli)
      run: npm install -g firebase-tools
      
    - name: Deploy the pages
      run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
